- name: install dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: no
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - nmap
- name: get docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: no
- name: install docker
  apt:
    name: "{{item}}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: enable docker service
  service:
    name: docker
    state: started
    enabled: yes
- name: Install docker python module
  pip:
    name: docker
    state: latest
  

