- name: Delete volume if it exists
  file:
    path: /jenkins_volume
    state: absent
  ignore_errors: yes
- name: Give permission for a volume
  file:
    path: /jenkins_volume
    state: directory
    owner: root
    group: root
    mode: 0777
- name: Stop container if it is running
  docker_container:
    name: jenkins
    state: stopped
  ignore_errors: yes
- name: Run jenkins as a docker container
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /jenkins_volume:/var/jenkins_home
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=true"
  register: jenkins_container
  changed_when: jenkins_container is changed

# - name: Wait for jenkins to start
#   uri:
#     url: http://localhost:8080
#     status_code: 200
#   register: jenkins_status
#   until: jenkins_status.status == 200
#   retries: 10
#   delay: 10