- name: Update packages
  apt:
    update_cache: yes

- name: Install python dependencies
  apt:
    name: "{{item}}"
    state: present
  loop:
    - python3-pip
    - python3-apt
    - python3-docker