- name: Install plugins in jenkins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
    url: http://jenkinsm.pwasil.pl:8080
    with_dependencies: yes
  loop:
    - pipeline
    - github
    - build-pipeline-plugin
    - git
    - ldap
    - ssh-agent
    - ssh-slaves
    - gradle
    - pipeline-model-definition
    - jclouds-jenkins
    - pipeline-stage-view
    - nexus-artifact-uploader
    - artifact-promotion
    - docker-workflow

- name: Stop jenkins in container
  docker_container:
    name: jenkins
    state: stopped

- name: Start jenkins in container
  docker_container:
    name: jenkins
    state: started

- name: Wait for jenkins to start
  uri:
    url: http://jenkinsm.pwasil.pl:8080
    status_code: 200
  register: result
  until: result.status == 200
  retries: 10
  delay: 5

