- name: install dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: no
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - gpg

- name: add PGP key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.pgp

- name: convert GPG key
  command: gpg --dearmor --batch --yes --output /etc/apt/trusted.gpg.d/docker.gpg /tmp/docker.pgp

- name: add repository
  apt_repository:  
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
    state: present
    update_cache: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: enable docker
  service:
    name: docker
    state: started
    enabled: yes

